blank_issues_enabled: false

contact_links:
  - name: Discussions
    url: https://github.com/SunnyJayaRaju/workstation-framework/discussions
    about: Please use Discussions for questions and ideas.